/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type RobotJS = RobotJs
export declare class RobotJs {
  constructor()
  dragMouse(x: number, y: number, button?: string | undefined | null): number
  updateScreenMetrics(): number
  moveMouse(x: number, y: number): number
  moveMouseSmooth(x: number, y: number, speed?: number | undefined | null): number
  getMousePos(): object
  mouseClick(button?: string | undefined | null, double?: boolean | undefined | null): number
  mouseToggle(down?: string | undefined | null, button?: string | undefined | null): number
  setMouseDelay(delay: number): number
  scrollMouse(x: number, y: number): number
  keyTap(key: string, modifiers?: Array<string> | undefined | null): number
  keyToggle(key: string, down?: string | undefined | null, modifiers?: Array<string> | undefined | null): number
  unicodeTap(value: string): number
  typeString(string: string): number
  typeStringDelayed(string: string, cpm: number): number
  setKeyboardDelay(delay: number): number
  getPixelColor(x: number, y: number): string
  getScreenSize(): object
  captureScreen(x?: number | undefined | null, y?: number | undefined | null, width?: number | undefined | null, height?: number | undefined | null): object
  getColor(img: object, x: number, y: number): string
  getXDisplayName(): string
  setXDisplayName(name: string): number
}
